package com.example.myapplication.model;

import android.graphics.Bitmap;
import android.net.Uri;

import com.example.myapplication.datasystem.DataCaptureSettings;
import com.example.myapplication.sampler.CircularSamplerGenerator;

/**
 * Contains Data aspect from the DataCaptureActivity (ViewModel paradigm)
 */
public class DataCaptureModel {

    /**
     * user settings
     */
    private static DataCaptureSettings settings;

    /**
     * Bitmap to display on screen
     */
    private Bitmap pictureBitmap;

    private Uri pictureBitmapUri;

    /**
     * Samplers generated by user
     */
    private CircularSamplerGenerator csGen;

    public DataCaptureModel() {

    }

    public Uri getPictureFileUri() {
        return pictureBitmapUri;
    }
}
